const StringConstants = {
  hi: "Hi",
  upload: "Upload",
  "nav.invoices": "Invoices",
  "nav.settings": "Customize",
  "nav.invoice": "Invoice",
  "nav.design": "Design",
  "nav.customer": "Customer",
  "nav.company": "Company",
  "nav.email": "Email",
  "nav.footer": "Footer",
  "nav.heading": "Headings",
  "nav.support": "Support",
  "nav.pricing": "Pricing",
  "image.girl": "Smiling Woman",
  "image.downArrow": "Down Arrow",
  "error.color":
    "Please provide a hexadecimal color code with a leading number sign(e.g #00FF00)",
  "error.legalName": "Legal name of business is required.",
  "error.invoiceNumber": "Starting invoice number is required.",
  "error.sendAutomatic":
    "Atleast one state should be enabled if send invoices automatically is yes",
  "error.fromEmailId": "Invoices will be sent from this email id is required.",
  "error.bulkEmailId":
    "Bulk Invoices will be sent to this email id is required.",
  "error.fromName": "Invoices will be sent on this name is required.",
  "error.subject": "Invoices email subject is required.",
  "error.emailMessage": "Invoices email message is required.",
  "error.invalisSubjectOrMessage":
    "Invalid usage of standard variables. Use variables exactly same as given below.",
  "error.invalid.emailId": "Email id is not valid.",
  "error.invalid.noEmailId": "Email id is required.",
  "error.sameAs.fromEmailId": "Enter an email id except {fromEmailId}",
  "error.sectionHeading": "Heading for the section is required.",
  "error.company.address1": "Apartment, suite, etc is required.",
  "error.company.city": "City is required.",
  "error.company.postcode": "Postal/ZIP code is required.",
  "error.company.state": "State is required.",
  "error.company.country": "Country is required.",
  "error.email.additionalPDF": "Maximum 3 PDF(s) are allowed.",
  "error.image.format": "Only png, jpeg, jpg and gif file is allowed",
  "error.image.size": "Size greater than 100KB is not allowed",
  yes: "Yes",
  no: "No",
  advanced: "Advanced",
  edit: "Edit",
  remove: "Remove",
  uploadLogo: "Upload your logo",
  uploadSignature: "Upload your signature",
  done: "Done",
  next: "Next",
  success: "Success",
  copy: "COPY",
  save: "Save",
  send: "Send",
  resend: "Resend",
  on: "On",
  off: "Off",
  note: "Note",
  preview: "Preview",
  setDefault: "Set Default",
  store: "Your store",
  step: "Step",
  "dashboard.contextualSaveBar.sendToCustomers": "Send invoices to customers",
  "dashboard.contextualSaveBar.sendToMe": "Send individual invoices to me",
  "dashboard.contextualSaveBar.sendMergedToMe": "Send merged invoice to me",
  "dashboard.contextualSaveBar.mergedPdf": "Merged pdf",
  "dashboard.contextualSaveBar.mergedPdfToolTip":
    "You will receive merged pdf to your email id",
  "dashboard.actions.view": "View the invoice",
  "dashboard.actions.send": "Send the invoice to the customer",
  "dashboard.actions.resend": "Resend the invoice to the customer",
  "important.notice": "Important Notice",
  "recommended.settings": "Use Recommended Settings",
  "language.change": "Dashboard Language",
  "toast.language": "Language saved successfully",
  "toast.copied": "Copied",
  "toast.enabled": "Enabled Successfully",
  "toast.disabled": "Disabled Successfully",
  "toast.mailSent": "Mail sent successfully",
  "toast.save": "Saved successfully",
  "toast.planAlreadyActive": "Selected plan is already active",
  "toast.somethingWrong": "Sorry, something went wrong.",
  "toast.noTemplate": "No templates available.",
  "toast.validTemplate": "Select valid template",
  "toast.validEmail": "Please enter valid email address.",
  "toast.error.sameEmail":
    "You cannot use the same email id that is used in point 1 above.",
  "toast.error.email":
    "Mail sent unsuccessfully. Please try again after some time.",
  "screenShareMsg.msg1": "Need help?",
  "screenShareMsg.msg2":
    "Our experts will install the app for you. Simply send a mail to",
  "step.save": "Next",
  "step.back": "Back",
  customizeMoreLater: "Customize more from the app settings later!",
  "step1.heading": "Choose invoice design and the colors",
  "step1.note":
    "Select the design and the color for your invoice matching your brand",
  "step1.message": "Now you can also create beautiful invoices like any other",
  "step1.subMessage": "successful online businesses.",
  "step2.languageLabel": "Choose Your invoice language",
  "step2.invoiceBackgroundColorLabel": "Change your brand color for invoice",
  "step2.fileUploadLabel": "Upload your logo (optional)",
  "step2.fileDescription":
    "png, jpeg, jpg, gif having max 250x125px (100KB limit)",
  "step2.heading": "Enter your company details",
  "step2.message":
    "4000+ Shopify stores {subStr} for automating their invoices.",
  "step2.subMessage": "trust us",
  "step3.secondRowText": "Do you want to send invoices automatically?",
  "step3.sendInvoiceRadio": "Yes, Invoices will be sent from this email",
  "step3.dontSendInvoiceRadio":
    "No, But but when you send manually, invoices will be sent from this email",
  "step3.heading": "Customize important invoice settings",
  "step3.note":
    "We have prefilled all the options for you. Edit them if you want to change else click next below.",
  "step3.note.subMessage": "Fill the remaining empty fields",
  "step3.message":
    "4000+ Shopify stores {subStr} for automating their invoices.",
  "step3.subMessage": "trust us",
  "template.heading": "Invoice design",
  "template.heading.title": "Want custom invoice design?",
  "template.heading.note":
    "We will be releasing new designs every month. If you want to use custom Invoice design for your store, please send us your design to",
  "template.color": "My preferred color for the text",
  "template.backgroundColor": "My preferred color for the background",
  "template.headerTextColor": "My preferred color for the header text",
  "tax.name": "Tax name",
  "tax.number": "Tax number of your company (recommended)",
  "placeholder.tax.number": "Ex: GST 123456 or VAT 12345",
  language: "Invoice language",
  "language.subNote":
    "Now supporting {languageCount} languages. Contact us at {email} if you find any issues with our multi language invoices.",
  generateInvoiceOn: "Enable multi currency invoices",
  "generateInvoiceOn.note":
    "Enabling this will send the invoices in the same currency that your customer paid. We recommend to keep it",
  sendInvoiceAutomatically: "Send invoices automatically",
  "sendInvoiceAutomatically.heading":
    "Configure the situations when to send the invoices automatically",
  "sendInvoiceAutomatically.note":
    "Enabling this will save you a huge amounts of time. Your customers will get their pdf invoice immediately after their purchase via an email. We highly recommend to keep it",
  "sendInvoiceAutomatically.advance": "Advance settings",
  "sendInvoiceAutomatically.orderCreate": "Order creation",
  "sendInvoiceAutomatically.orderRefund": "Refund",
  "sendInvoiceAutomatically.orderCancel": "Order cancellation",
  "sendInvoiceAutomatically.orderEdit": "Order edit",
  "sendInvoiceAutomatically.orderAddressChange":
    "Customer's billing or shipping address change",
  "sendInvoiceAutomatically.emailChange": "Customer's email id change",
  legalName: "Legal name of your company (recommended)",
  "placeholder.legalName": "Enter legal name of my business",
  "placeholder.bccID": "Add email id",
  invoiceNumber: "Invoice numbers",
  "placeholder.invoiceNumber": "Enter your starting invoice #",
  "invoiceNumber.message": "Add Prefix & Postfix to the total invoice number",
  prefix: "Prefix",
  postfix: "Postfix",
  "placeholder.prefix": "Enter prefix",
  "placeholder.postfix": "Enter postfix",
  "prefix.postfix.note":
    "Enter ABC in prefix and PQR in postfix, if you want your invoice numbering like ABC<number>PQR",
  "comapny.logo": "Logo (optional)",
  "company.signature": "Company signature",
  logo: "logo",
  removeLogo: "Remove logo",
  "logo.note2": "Format: png, jpeg, jpg and gif",
  "logo.note3": "Recommended Resolution: 250×125 px (100KB limit)",
  "signature.note3": "Recommended resolution 200×50 px",
  signature: "signature",
  "step4.secondRowText":
    "A small note about tax, currency settings and invoices for existing orders",
  "step4.cardText":
    "Your invoices will be created using the tax and multi currency settings in your Shopify admin. You do not need to worry!",
  "step4.heading": "Email settings for sending invoices",
  "step4.note":
    "We have prefilled all the options for you. Edit them if you want to change else click next below.",
  "step4.message":
    "We are one of the very few apps who sends PDF invoices as an {subStr} itself.",
  "step4.subMessage": "attachment in the email",
  "pricing.hurray": "Hurray!",
  "pricing.off": "off",
  "pricing.lastStep": "Last Step",
  "pricing.freeTrial1": "Start your free trial now",
  "pricing.freeTrial2": "and never worry about invoicing for your store!",
  "pricing.choosePlan": "Choose your plan:",
  "pricing.bestValue": "Best Value",
  "pricing.month": "mo",
  "pricing.paidPlanCardText":
    "You'll send 12% of your daily sales until you've remitted $8,475.",
  "pricing.freePlanCardText":
    "You'll send 10% of your daily sales until you've remitted $5,650.",
  "pricing.freeTrial": "Free Trial",
  "pricing.chooseThis": "Choose This",
  "pricing.seeMoreDetails": "See more details",
  "pricing.seeLessDetails": "See less details",
  "pricing.plan_free.item1": "Multiple Invoice designs",
  "pricing.plan_free.item2": "Print, send & download invoices",
  "pricing.plan_free.item3": "Best support",
  "pricing.plan_one.item1": "Multiple Invoice designs",
  "pricing.plan_one.item2": "Automatic invoice creation and sending",
  "pricing.plan_one.item3": "Multi-currency support",
  "pricing.plan_one.item4": "Multi-language support (61 languages)",
  "pricing.plan_one.item5": " Set Custom invoice number",
  "pricing.plan_one.item6": "Include your invoice terms & conditions",
  "pricing.plan_one.item7": "Send the invoices to your customers in bulk",
  "pricing.plan_one.item8": "Download the invoices in bulk",
  "pricing.plan_one.item9": "Customize the emails (content & subject)",
  "pricing.plan_one.item10": "Send marketing pdfs (coming soon)",
  "pricing.plan_one.item11": "Generate proforma invoices",
  "pricing.plan_one.item12": "Priority support",
  "pricing.plan_two.item1": "Multiple Invoice designs",
  "pricing.plan_two.item2": "Automatic invoice creation and sending",
  "pricing.plan_two.item3": "Multi-currency support",
  "pricing.plan_two.item4": "Multi-language support (61 languages)",
  "pricing.plan_two.item5": " Set Custom invoice number",
  "pricing.plan_two.item6": "Include your invoice terms & conditions",
  "pricing.plan_two.item7": "Send the invoices to your customers in bulk",
  "pricing.plan_two.item8": "Download the invoices in bulk",
  "pricing.plan_two.item9": "Customize the emails (content & subject)",
  "pricing.plan_two.item10": "Send marketing pdfs (coming soon)",
  "pricing.plan_two.item11": "Generate proforma invoices",
  "pricing.plan_two.item12": "Priority support",
  "pricing.plan_three.item1": "Multiple Invoice designs",
  "pricing.plan_three.item2": "Automatic invoice creation and sending",
  "pricing.plan_three.item3": "Multi-currency support",
  "pricing.plan_three.item4": "Multi-language support (61 languages)",
  "pricing.plan_three.item5": " Set Custom invoice number",
  "pricing.plan_three.item6": "Include your invoice terms & conditions",
  "pricing.plan_three.item7": "Send the invoices to your customers in bulk",
  "pricing.plan_three.item8": "Download the invoices in bulk",
  "pricing.plan_three.item9": "Customize the emails (content & subject)",
  "pricing.plan_three.item10": "Send marketing pdfs (coming soon)",
  "pricing.plan_three.item11": "Generate proforma invoices",
  "pricing.plan_three.item12": "Priority support",
  "pricingOffer.titleRow2": "An important info to you!",
  fromEmailId: "Invoices will be sent from this email id",
  fromName: "Invoices will be sent on this name",
  subject: "Invoices email subject",
  templateVariable: "Template Variables",
  emailMessage: "Invoices email message",
  sendCopyTo: "Send the invoices to the following email ids as bcc (max 5 ids)",
  "step5.heading":
    "Hurray! Installation is successful. Send a test invoice to your email id",
  "step5.note":
    "Use different email than email you used for sent email id from in step 4. Otherwise you will see warning message in mail from google due to gmail policy",
  "step5.message":
    "Join the 4000+ stores who automated their invoice to their customers.",
  "testEmail.message2": "Let us send a test invoice to your email id.",
  emailId: "Enter an email id {subStr} to receive a test invoice",
  "emailId.subMsg": "(except {fromEmailId})",
  sendSampleInvoice: "Send Sample Invoice",
  "testEmail.success": "Success! Please check your email",
  "testEmail.success.message1":
    "Look at the invoice design and the email content carefully and choose an option from below.",
  "testEmail.goToDashboard": "Perfect! Go to last step",
  "testEmail.installationAgain": "I want to go back and edit",
  "review.heading":
    "Hurray Last Step: We truly appreciate if you could take 10 seconds to give us a 5 star review.Your reviews boost our team morale to move forward.",
  sampleReview: "Sample review",
  "review.share": "Share your love with us",
  "review.later": "No thanks, I will do later",
  "design.header": "Customize your invoice design",
  "design.headingFont": "Heading font",
  "design.textFont": "Text font",
  "design.lineItemSettings": "Line items settings (for each product)",
  "design.lineItemSettings.sub": "Choose the sections for product description",
  "design.summarySettings": "Summary settings",
  "design.summarySettings.sub":
    "Display the following fields even if their value is zero",
  "design.generalSettings": "General settings",
  "design.displayCurrencyCode":
    "Display price with ISO currency code (ex. $12 USD)",
  "design.displayTax": "Display tax amount for each product",
  "design.displayDiscount": "Display discount even if its value is zero",
  "design.displayFinalUnitPrice":
    "Display final unit price for each product also",
  "design.displaySKU": "SKU",
  "design.displayBarcode": "Barcode",
  "design.displayCountyOfOrigin": "Country Of Origin",
  "design.displayHSCode": "HS Code",
  "design.displayProductImage": "Images",
  "design.displaySubtotalAfterDiscount":
    "Display subtotal after discount in summary",
  "design.displaySubtotalExcluded":
    "Display subtotal without tax and discount in summary",
  "design.displayTaxIfNonEmptyInSummary": "Tax",
  "design.displayDiscountIfNonEmptyInSummary": "Discount",
  "design.displayShippingIfNonEmptyInSummary": "Shipping",
  "design.displayTipIfNonEmptyInSummary": "TIP",
  "design.displayDeliveryMethod": "Display shipping method in shipping summary",
  "design.displayLast4DigitCardNumber":
    "Include the payment details (card type & last 4 digits of the card)",
  "design.displayIndividualTax":
    "Display individual tax details (if multiple taxes are applied)",
  "design.displaySignature": "Display signature",
  "design.displayComputerGeneratedMsg":
    "Display computer generated message for not required signature",
  "design.message":
    "Join the 4000+ stores who automated their invoice to their customers.",
  "customer.heading":
    "Edit the customer data that you want to show in your invoice",
  sectionHeading: "Heading for the section",
  "customer.message":
    "Join the 4000+ stores who automated their invoice to their customers.",
  "customer.displayPhone": "Display customer's phone number",
  "customer.displayEmail": "Display customer's email",
  "customer.displayCountry": "Display customer's country",
  "customer.displayShippingAddress": "Display customer's address",
  "shipping.heading": "Shipping address heading",
  "shipping.displayPhone": "Display customer's phone number",
  "shipping.displayEmail": "Display customer's email",
  "shipping.displayCountry": "Display customer's country",
  "company.heading":
    "Edit the company data that you want to show in your invoice",
  "company.message":
    "Join the 4000+ stores who automated their invoice to their customers.",
  "company.emailId": "Company support email id",
  "company.bulkEmailId": "Company email id for bulk invoice download",
  "company.website": "Company website",
  "company.editStoreAddress": "Edit the store address",
  "company.additionalField": "Edit additonal text",
  "company.storeName": "Store name",
  "company.phone": "Phone",
  "company.address1": "Apartment, suite, etc.",
  "company.address2": "Street",
  "company.city": "City",
  "company.postcode": "Postal/ZIP code",
  "company.state": "State",
  "company.country": "Country",
  "email.heading": "Edit your email settings",
  "email.message":
    "Join the 4000+ stores who automated their invoice to their customers.",
  "email.additionalPDF": "Additional PDF file attached to every email (max 3)",
  "email.additionalPDF.currentlyUploaded": "Current uploaded file",
  "email.sureWantToDelete": "Are you want to remove",
  "footer.heading": "Edit the content in your invoice footer section",
  "footer.message":
    "Join the 4000+ stores who automated their invoice to their customers.",
  "footer.additionalText": "Additional text in invoice footer",
  "footer.thankYouNote": "Thank you note",
  "support.heading": "Help & Support",
  "support.message1":
    "Need any help with setup or customization? Our team is always there to resolve your queries.",
  "support.message2.part1": "Send a mail us at",
  "support.message2.part2":
    "and our awesome support team will get back to you within 24 hours.",
  "support.message3.part1": "Note:",
  "support.message3.part2": "Please provide your store access to",
  "support.message3.part3": ", if it requires us to access your store.",
  "dashboard.noInvoice": "Manage your invoices",
  "dashboard.noInvoice.desc":
    "Once your store has orders, this is where you'll see the corresponding invoices.",
  "placeholder.searchOrder": "Search your order",
  "dashboard.entries": "entries",
  "dashboard.number": "Invoice",
  "dashboard.order": "Order",
  "dashboard.date": "Date",
  "dashboard.name": "Name",
  "dashboard.total": "Total",
  "dashboard.status": "Status",
  "dashboard.noData": "No data found!",
  "welcome.impMessage": "Important Message. Please read",
  "welcome.message1": "Hi",
  "welcome.signupThankyou": "Thanks for signing up!",
  "welcome.cardText":
    "We know you're excited to send beautiful invoices to your customers automatically.",
  "welcome.message2":
    "I'm Amrish, the CEO of MLVeda. I wanted to personally welcome you and help you setup fire AMP app on your store.",
  "welcome.message3":
    "I will guide you step by step. At any point if you need any help feel free to send a mail to",
  "welcome.message4": "I wish huge success to you and your store.",
  "welcome.intro":
    "I’m {subStr1}, the co-creator of this app. First of all, I want to thank you for the {subStr2} you have bestowed on us by installing our app. Your {subStr2} will increase our {subStr3}.",
  "welcome.intro.subMsg1": "Rajesh",
  "welcome.intro.subMsg2": "trust",
  "welcome.intro.subMsg3": "responsibility",
  "welcome.headingText": "Design like the best for any platform",
  "welcome.message1Text": "Rated 4.8 in Shopify App store.",
  "welcome.message2Text": "Trusted by more than 4000+ Stores.",
  "welcome.openAccountButton.openAccount": "Open Account",
  "welcome.openAccountButton.itsFree": "it's free",
  "welcome.rated": "Rated",
  "welcome.mustInstall": "We are one of the few {subStr} in Shopify.",
  "welcome.mustInstall.subMsg1": "must install apps",
  "welcome.backbone": "We are like backbone for Shopify stores.",
  "welcome.rule.message":
    "I and my small team at Invoicing Hero follow the below two simple rules",
  "welcome.rule": "Rule",
  "welcome.rule1.message":
    "Take care of all the invoice related things for a Shopify store",
  "welcome.rule2.message": "Never forget rule No. 1",
  "welcome.team.title": "An app is as good as its team:",
  "welcome.team.message1":
    "Invoice Hero is built by an incredibly talented and dedicated team. We're almost 40% women and 100% culturally diverse team.",
  "welcome.team.message2": "Most importantly we are all ",
  "welcome.team.message3":
    "trustworthy and compassionate human beings to do business with.",
  "welcome.isntall.title": "Our app purpose",
  "welcome.isntall.message1":
    "Our app helps not only in the creation of beautiful invoices, but also send those pdf invoices automatically to your customers when they buy from your store. Thus saving a lot of time, effort, and money for you.",
  "welcome.step.title":
    "To complete the setup, you can choose one of the options given below.",
  "welcome.step1.msg1":
    "Simply follow the four easy steps. It does not require any coding at all. We have also prefilled most of the settings for you.",
  "welcome.step1.msg2":
    "anyone with zero technical skills can set up the app easily on their Shopify store",
  "welcome.or": "OR",
  "welcome.step2.msg1": "Send us a mail at",
  "welcome.step2.msg2":
    "I or someone will help you to install the app over a screen sharing call (Zoom/Google Meet) at your convenience.",
  "welcome.knowMore":
    "To know more about our app and our vision, please read the below message as well:",
  "welcome.bestThing":
    "One of the best things about our app is, we release a new update once every two weeks. This will make sure that you get new invoice designs and feature improvements immediately.",
  "welcome.cheers": "Cheers",
  "welcome.yourFriend": "Rajesh and Your Friends at Invoice Hero",
  "welcome.startSetup": "Let's Start",
  "welcome.noTime": "Takes about two minutes",
  "appTopBar.tab.installation": "INSTALLATION",
  "appTopBar.tab.help": "HELP",
  new: "new",
  "step1.hi": "Hi",
  "welcome.quickSetup": "Let's do a quick setup",
  "step1.legalName.label": "legal name of my business",
  "step1.email.label": "Invoices will be sent from this email id",
  "step1.colorCode.label": "Color code",
  "step1.note.title": "A Note about invoices for your existing orders:",
  "step1.note.content":
    "We will create invoices automatically for your old orders as well.",
  "step1.canCustomizeString":
    "You can customize completely from our settings section later",
  "sidebar.upgradeNow": "Upgrade Now",
  "sidebar.off": "off",
  "sidebar.lifetime": "Lifetime",
  "header.invoiceHero": "INVOICE HERO",
  "header.no1App": "No. 1 invoice app for Shopify stores",
  "header.appStatus": "Automate Invoices",
  "header.enableDisableMsg":
    "Do you want to {value} automatic sending invoices?",
  "header.enable": "enable",
  "header.disable": "disable",
  "appFooter.helpText": "We’re here to help you.",
  "appFooter.supportText.msg1":
    "Whether you’ve a small query or big issue, please schedule a meeting with us below or send us an email at",
  "appFooter.supportText.msg2":
    "We are committed to serving you within 24 hours.",
  "multilingual.orderNote": "Notes",
  "multilingual.invoice": "Invoice",
  "multilingual.paidByCustomer": "Paid by customer",
  "multilingual.outstandingCustomerOwes": "Outstanding (Customer owes)",
  "multilingual.outstandingOwnerOwes": "Outstanding (Store owner owes)",
  "multilingual.netPayment": "Net Payment",
  "multilingual.draftInvoice": "Proforma Invoice",
  "multilingual.included": "Included",
  "multilingual.excluded": "Excluded",
  "multilingual.subtotalAfterDiscount": "Subtotal after discount",
  "multilingual.paymentHeading": "Payment Details",
  "multilingual.paymentGateway": "Payment Gateway",
  "multilingual.cardType": "Card Type",
  "multilingual.cardNumber": "Card Number",
  "multilingual.tip": "Tip",
  "multilingual.invoiceNumber": "Invoice Number",
  "multilingual.duties": "Duties",
  "multilingual.issueDate": "Issue Date",
  "multilingual.billingHeading": "Billing Details",
  "multilingual.shippingHeading": "Shipping Details",
  "multilingual.companyHeading": "Company Details",
  "multilingual.customerHeading": "Customer Details",
  "multilingual.description": "Description",
  "multilingual.sku": "SKU",
  "multilingual.barcode": "Barcode",
  "multilingual.countryOfOrigin": "Country of origin",
  "multilingual.hsCode": "HS code",
  "multilingual.unitPrice": "Unit Price",
  "multilingual.finalUnitPrice": "Unit Price (final)",
  "multilingual.quantity": "Quantity",
  "multilingual.total": "Total",
  "multilingual.tax": "Tax",
  "multilingual.signature": "Signature",
  "multilingual.subtotal": "Subtotal",
  "multilingual.discount": "Discount",
  "multilingual.shipping": "Shipping",
  "multilingual.support": "Support",
  "multilingual.company": "Company",
  "multilingual.refunded": "Refund",
  "multilingual.products": "Product(s):",
  "multilingual.including": "Including",
  "multilingual.productPlusShipping": "Products + Shipping",
  "multilingual.netTotal": "Net Total",
  "multilingual.draftInvoiceHeading": "	Proforma Invoice",
  "multilingual.via": "Via",
  "multilingual.item": "Item",
  "multilingual.items": "Items",
  "multilingual.weight": "Weight",
  "language.popup.msg1":
    "You are changing your invoice language from {fromLang} to {toLang}. This will also over write all the custom changes you made for headings, email & footer sections.",
  "language.popup.msg2": "Are you sure want to change the languge?",
  "your.language": "Your invoice language",
  "setDefault.all": "Set default for all the fields",
  "heading.heading": "Edit the headings of your invoice",
  "settings.heading": "Edit important invoice settings",
  "language.note":
    "The default values of the below fields are determined by your invoice language. Currently your invoice language is set to {subStr}.",
};

export default StringConstants;
